from .cors import CORS_MIDDLEWARE
from .database import DATABASE_MIDDLEWARE
from .trusted_host import TRUSTED_HOST_MIDDLEWARE

MIDDLEWARES = [CORS_MIDDLEWARE, DATABASE_MIDDLEWARE, TRUSTED_HOST_MIDDLEWARE]
