version: '3.8'

services:

  library_api:
    container_name: library_api
    build: .
    command: >
      sh -c "alembic upgrade head && uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    env_file:
      - envs/docker/local/api
    volumes:
      - ./src:/code/src
      - ./alembic:/code/alembic
      - ./alembic_insertions:/code/alembic_insertions
      - ./alembic.ini:/code/alembic.ini
      - ./envs:/code/envs
    depends_on:
      library_db:
        condition: service_healthy

  library_db:
    container_name: library_db
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - envs/docker/local/db
    ports:
      - 5432:5432
    volumes:
      - .docker/volumes/postgres-data:/var/lib/postgres/data
