"""empty message

Revision ID: 37b06a7c4602
Revises: 
Create Date: 2023-04-23 23:28:22.436405

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Session

from alembic import op
from alembic_insertions import DomainV0

# revision identifiers, used by Alembic.
revision = "37b06a7c4602"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table", sa.String(), nullable=True),
        sa.Column("field", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "book",
        sa.Column("guid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("isbn", sa.String(), nullable=True),
        sa.Column("id_genre", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["id_genre"], ["domain.id"]),
        sa.PrimaryKeyConstraint("guid"),
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = Session(bind=bind)
    domain_v0 = DomainV0(session)
    domain_v0.execute()
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book")
    op.drop_table("domain")
    # ### end Alembic commands ###
