"""empty message

Revision ID: ed73b3cff944
Revises: 37b06a7c4602
Create Date: 2023-05-02 21:08:00.069277

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed73b3cff944"
down_revision = "37b06a7c4602"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.add_column("book", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("book", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "updated_at")
    op.drop_column("book", "created_at")
    op.drop_column("book", "deleted")
    # ### end Alembic commands ###
