"""empty message

Revision ID: ad8d162e808a
Revises: 15d0f1c2e971
Create Date: 2023-12-09 11:18:57.817195

"""
from alembic import op
from alembic_insertions.base_queries import BaseQueries
from alembic_insertions.v1_load import V1Queries

# revision identifiers, used by Alembic.
revision = "ad8d162e808a"
down_revision = "15d0f1c2e971"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    queries = V1Queries(op)
    queries.upgrade()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    queries = V1Queries(op)
    queries.downgrade()
    # ### end Alembic commands ###
